# Datasets are already TSV files
datasets:
  clean: test-data/clean.enzh.10

stages:
  - start
  - end

start:
  mix:
    - clean 1
    - until clean 1
  modifiers:
    - Tags: 0.5
      custom_detok_src: null
      custom_detok_trg: null
      template: "{src} __target__ {trg} __done__"

end:
  mix:
    - clean 1
    - until clean 1
  modifiers:
    - Tags: 0.5
      custom_detok_src: null
      custom_detok_trg: zh
      template: "{src} __target__ {trg} __done__"

seed: 1111
trainer: cat
